server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/asaavedras-dev/microservices-tutorial
          search-path: config-data
  application:
    name: config-service